# Copyright 2011 The Graphics-Go Authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

include $(GOROOT)/src/Make.inc

TARG=graphics-go.googlecode.com/hg/graphics/detect
GOFILES=\
	detect.go\
	doc.go\
	integral.go\
	opencv_parser.go\
	projector.go\

include $(GOROOT)/src/Make.pkg
